### PR TITLE
Update Yiqing profile

### PR DESCRIPTION
**Pull request by yiqings**
Update Yiqing's profile

### CODE REVIEW

**Comment by benjamindkilleen** [comment]
Sorry, I reverted this after spotting an error.

**Comment by yiqings** [comment]
Hi @benjamindkilleen, thanks! Could you specify the error such that I can fix it

**Comment by yiqings** [comment]
Thank you so much @benjamindkilleen 

My bad, I should have checked the image formatting before PR.

**Comment by benjamindkilleen** [comment]
No worries. I should have checked the deploy before merging

**Pull request merged**
